import fs from "fs";
import peggy from "peggy";

const grammar = fs.readFileSync("motion.pegjs", "utf8");
const parserCode = peggy.generate(grammar, { output: "source", format: "es" });

const content = `// Auto-generated by generate-parser.mjs
${parserCode}`;

fs.writeFileSync("src/motionParser.js", content);
console.log("✅ motionParser.js generated.");
